AMPGO02_meta = Dict(
  :nvar => 1,
  :variable_size => false,
  :ncon => 0,
  :variable_con_size => false,
  :minimize => true,
  :name => "AMPGO02",
  :has_equalities_only => false,
  :has_inequalities_only => false,
  :has_bounds => false,
  :has_fixed_variables => false,
  :objtype => :other,
  :contype => :unconstrained,
  :cvx_obj => missing,
  :cvx_feasible_set => true,
  :cqs => 0,
  :optimal_value => NaN,
  :has_multiple_solutions => missing,
  :is_infeasible => false,
  :defined_everywhere => missing,
  :origin => :unknown,
  :deriv => UInt8(0),
)
get_AMPGO02_meta(; n::Integer = default_nvar) = (1, 0)
