module OptimizationProblems

using JuMP

include("arwhead.jl")
include("bdqrtic.jl")
include("broydn7d.jl")
include("brybnd.jl")
include("chainwoo.jl")
include("cosine.jl")
include("cragglvy.jl")
include("curly.jl")
include("dixmaan_efgh.jl")
include("dixmaan_ijkl.jl")
include("dixmaan_mnop.jl")
include("dqrtic.jl")
include("edensch.jl")
include("eg2.jl")
include("engval1.jl")
include("genrose.jl")
include("genrose_nash.jl")
include("chnrosnb_mod.jl")
include("errinros_mod.jl")
include("extrosnb.jl")
include("fletcbv3_mod.jl")
include("fletcbv2.jl")
include("fletchcr.jl")
include("fminsrf2.jl")
include("freuroth.jl")
include("genhumps.jl")
include("indef_mod.jl")
include("liarwhd.jl")
include("morebv.jl")
include("ncb20.jl")
include("ncb20b.jl")
include("noncvxu2.jl")
include("noncvxun.jl")
include("nondia.jl")
include("nondquar.jl")
include("penalty2.jl")
include("penalty3.jl")
include("powellsg.jl")
include("sbrybnd.jl")
include("scosine.jl")
include("schmvett.jl")
include("sinquad.jl")
include("sparsine.jl")
include("sparsqur.jl")
include("srosenbr.jl")
include("tointgss.jl")
include("tquartic.jl")
include("woods.jl")

include("hs6.jl")
include("hs7.jl")
include("hs8.jl")

end # module
